/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "color-dark-100": "var(--color-dark-100)",
        "color-dark-1000": "var(--color-dark-1000)",
        "color-dark-250": "var(--color-dark-250)",
        "color-dark-50": "var(--color-dark-50)",
        "color-dark-500": "var(--color-dark-500)",
        "color-dark-750": "var(--color-dark-750)",
        "color-light-100": "var(--color-light-100)",
        "color-light-1000": "var(--color-light-1000)",
        "color-light-250": "var(--color-light-250)",
        "color-light-50": "var(--color-light-50)",
        "color-light-500": "var(--color-light-500)",
        "color-light-750": "var(--color-light-750)",
        "color-primary-100": "var(--color-primary-100)",
        "color-primary-1000": "var(--color-primary-1000)",
        "color-primary-500": "var(--color-primary-500)",
        colorsblack: "var(--colorsblack)",
      },
      fontFamily: {
        "body-regular-lg": "var(--body-regular-lg-font-family)",
        "body-regular-md": "var(--body-regular-md-font-family)",
        "body-regular-sm": "var(--body-regular-sm-font-family)",
        "body-regular-xl": "var(--body-regular-xl-font-family)",
        "body-regular-xs": "var(--body-regular-xs-font-family)",
        "body-regular-xxl": "var(--body-regular-xxl-font-family)",
        "body-semibold-lg": "var(--body-semibold-lg-font-family)",
        "body-semibold-md": "var(--body-semibold-md-font-family)",
        "body-semibold-sm": "var(--body-semibold-sm-font-family)",
        "body-semibold-xl": "var(--body-semibold-xl-font-family)",
        "body-semibold-xs": "var(--body-semibold-xs-font-family)",
        "body-semibold-xxl": "var(--body-semibold-xxl-font-family)",
        "headings-h1": "var(--headings-h1-font-family)",
        "headings-h2": "var(--headings-h2-font-family)",
        "headings-h3": "var(--headings-h3-font-family)",
        "headings-h4": "var(--headings-h4-font-family)",
        "headings-h5": "var(--headings-h5-font-family)",
        "headings-h6": "var(--headings-h6-font-family)",
        "headings-h7": "var(--headings-h7-font-family)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
